package game;

public enum BasicGameTypes {
        PLAYER, WALL, PASSABLE, PASSABLETRIGGER, MOVING, MOVINGSTOP, AMMOBOX, BULLET,
        ENEMY, ENEMYBULLET, ELITEENEMY, MOVINGENEMY,
        START, EXIT, SIDEDOOR, SIDEDOORTRIGGER, KEYCARD, TELEPORTER
}
