package game;

public enum BasicGameTypes {
        PLAYER, WALL, BREAKABLEWALL, HIDDEN, PASSABLE, PASSABLETRIGGER, MOVING, MOVINGSTOP, AMMOBOX, BULLET,
        ENEMY, ENEMYBULLET, ELITEENEMY, MOVINGENEMY,
        START, EXIT, EXITSWITCH, SIDEDOOR, SIDEDOORTRIGGER, KEYCARD, TELEPORTER, ONEWAYTELEPORT, OWTDROPOFF
}
