package game;

public enum BasicGameTypes {
        PLAYER, WALL, BREAKABLEWALL, HIDDEN, PASSABLE, PASSABLETRIGGER, MOVING, MOVINGSTOP, AMMOBOX, BULLET,
        TURRET, ENEMYBULLET, ELITETURRET, MOVINGENEMY, ELITEMOVINGENEMY,
        START, EXIT, EXITSWITCH, SIDEDOOR, SIDEDOORTRIGGER, KEYCARD, TELEPORTER, ONEWAYTELEPORT, OWTDROPOFF
}
