package game;

public enum BasicGameTypes {
        PLAYER, WALL, BREAKABLEWALL, HIDDEN, HIDDENROOM, PASSABLE, PASSABLETRIGGER, MOVING, MOVINGSTOP, AMMOBOX, MEDKIT, BULLET, ROCKET, SG, MG, RL,
        TURRET, ENEMYBULLET, ELITETURRET, MOVINGENEMY, ELITEMOVINGENEMY, ROCKETDUMMY, BARONOFHELL, NORMALBOH, BOHTRIGGER, PURPLEBOH, PURPLEBOHEXPLOSION,
        START, EXIT, EXITSWITCH, SIDEDOOR, SIDEDOORTRIGGER, KEYCARD, TELEPORTER, ONEWAYTELEPORT, OWTDROPOFF
}
