package game;

public enum BasicGameTypes {
        PLAYER, WALL, BREAKABLEWALL, HIDDEN, PASSABLE, PASSABLETRIGGER, MOVING, MOVINGSTOP, AMMOBOX, BULLET, ROCKET,
        TURRET, ENEMYBULLET, ELITETURRET, MOVINGENEMY, ELITEMOVINGENEMY, ROCKETDUMMY, BARONOFHELL, NORMALBOH, BOHTRIGGER, PURPLEBOH, PURPLEBOHEXPLOSION,
        START, EXIT, EXITSWITCH, SIDEDOOR, SIDEDOORTRIGGER, KEYCARD, TELEPORTER, ONEWAYTELEPORT, OWTDROPOFF
}
